apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-553c
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-553c
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-553c
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-553c
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-553c
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-nrmo-tenant/rhtap-demo-app/hacbs-test-project-553c@sha256:fffd97ae4c16280956fdd7fd753df803903b71b05a31367e419d1e6e6ea5d287
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
